language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -e .
  - pip list
script:
  - python pep8.py --testsuite testsuite
  - python pep8.py --statistics pep8.py
  - python pep8.py --doctest
  - python setup.py test
matrix:
  allow_failures:
    - python: pypy
